# Generated by Django 6.1 on 2026-08-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday / Party', 'Birthday / Party'), ('Engagement', 'Engagement'), ('Haldi / Mehndi', 'Haldi / Mehndi'), ('Corporate Event', 'Corporate Event'), ('Dulha Rath and Roadlight', 'Dulha Rath and Roadlight'), ('Pickup Rental', 'Pickup Rental'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.TextField(help_text='Enter one feature per line.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='ICON', max_length=10),
        ),
    ]
