services:
  - type: web
    name: shivani-light-events
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shivani_lights.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false